### PR TITLE
Issues with permissions on django 2.1

### PR DESCRIPTION
**Pull request by theKomix**
I fixed permissions on django 2.1
Now you can use has_add_permission, has_change_permission and has_delete_permission in you ModelAdmin.

### CODE REVIEW

**Comment by fdintino** [comment]
There are a bunch of unrelated changes here that seem to be refactoring other code; do you mind if I only pull in the new permissions feature?

**Comment by fdintino** [comment]
You may also want to create a new branch and switch this PR to that, so that I can make edits directly to it without changing your master branch.

**Comment by theKomix** [comment]
All my changes affect to work inline forms with permissions.
I change NestedModelAdminMixin for support permissions and fix there one error.
I had to change templates. And I add template tag for better code in template.
I think my commits may be include in master branch.
Sorry for my English.

**Comment by theKomix** [comment]
Sorry, I changed url in setup.py.

**Comment by fdintino** [comment]
Thanks. To clarify, I think the template changes and the rename of `obj` to `form_or_formset` aren't related to adding permissions support.

The grappelli templates are written the way that they are so that they only have a few differences from the real grappelli inline templates. Compare: [grappelli template](https://github.com/sehmaschine/django-grappelli/blob/59646db60e3d49b65ccc244dd247a4cc6ef777d0/grappelli/templates/admin/edit_inline/stacked.html) vs. [nested-admin template](https://github.com/theatlantic/django-nested-admin/blob/599b539e5cecfe6c01936204f5f75ea73a419636/nested_admin/templates/nesting/admin/inlines/grappelli_stacked.html). That makes it easier for me to update the templates if grappelli makes changes between versions. So, although `{% ifemptyform %}` might be cleaner, I would not want to use it because it is not in the original grappelli template. The same thing is true for the regular stacked template: it is as similary as possible to the real django template while allowing nesting, and I'd like to keep it that way.

The part where you rename `obj` to `form_or_formset`: I can see why that some people might think that is a better variable name, but since it's not related to the permissions changes I think it ought to be removed.

The reason I suggested that you rename the branch on your repository is because I will want to make changes to this code before merging. Github allows me to do that when you open a pull request. So if you don't want me making changes to your master branch, it would be a good idea to rename it to something like `pr-support-permissions` or something. That way I could make these edits for you, and also add unit tests to verify that permissions now work.

**Comment by theKomix** [comment]
I rename obj to form_or_formset because variable obj was changed in loop and it's affected to inline_instance.get_inline_instances(request, obj). May be name isn't good but it's work.
I had to change templates because without my changes if a deny changes and add objects I got form without fields and data because the inlines array doesn't have empty-form for adding. 
I use your project and I want to do it better. Unfortunately, this is my first PR and I don't understand about "pr-support-permissions"

**Comment by fdintino** [comment]
Thank you for the explanation, that makes sense. I'll work on adding tests for the new feature and will post here when I've finished (it might not be for a few days)

**Comment by fdintino** [comment]
@theKomix can you check to see whether the latest master branch addresses your needs with inline permissions?

**Comment by fdintino** [comment]
It seems to me that the permissions issues are sorted in the latest release. If this is not the case, feel free to reopen this PR or a new ticket.

**Pull request closed without merging**
