### PR TITLE
fix nested inline classes

### PR DESCRIPTION
**Pull request by olivierdalang**
Nested inlines did not use the classes, so that it was impossible to collapse a nested inline. This PR fixes this.

```
class NestedInline( nested_admin.NestedStackedInline ):
    ...
    classes = ('grp-collapse grp-closed',) # doesn't work !!
    ....
```
```
class NormalInline( admin.StackedInline ):
    ....
    classes = ('grp-collapse grp-closed',)
    ....
```

Thanks for the great module !

### CODE REVIEW

**Comment by olivierdalang** [comment]
Oops do not merge I just found a bug it seems

**Comment by olivierdalang** [comment]
Ok it's better now. Not sure about the implementation, it's a quick fix without digging to deep in the code, but it seems to work here.

**Comment by philippeluickx** [comment]
+1

**Comment by fdintino** [comment]
This should be fixed with the 3.0 release.

**Pull request closed without merging**
